### ISSUE TITLE
How can I use in python3? A lot modules don't install

### ISSUE THREAD

**Issue by raphaelfmiranda** [cclgroupltd/ccl-bplist#1]
How can I use in python3? A lot modules don't install

**Comment by cclgroupltd** [comment]
This seems odd as the only imports used by the module are in the standard library. Could you explain in a little detail more what you have tried and what is going wrong?

**Comment by cclgroupltd** [comment]
Hi, I'm going to close this issue as without any further context it's not something we can look at. If you have some additional information please feel free to add it below or open a new issue and I'll be happy to look into it.
